//获取设备状态
// export const GET_DEVICESINFO = 'GET_DEVICESINFO';
export const SET_USERINFO = "SET_USERINFO";
export const SET_EQUITYLIST = "SET_EQUITYLIST";
export const SET_BABYINFO = "SET_BABYINFO";
export const SET_SYSTEM ="SET_SYSTEM";
export const SET_MEMBERINFO ="SET_MEMBERINFO";
export const SET_USERCID ="SET_USERCID";
export const SET_USERBABY="SET_USERBABY";
export const SET_COURSEDETAILS="SET_COURSEDETAILS";
export const SET_USERCOURSE ="SET_USERCOURSE"
